name: Publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'jsr.json'
      - 'CHANGELOG.md'
jobs:
  semantic_release:
    permissions:
      id-token: write
    name: Semantic release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.11.0
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

#  publish_jsr:
#    name: Publish to JSR
#    needs: semantic_release
#    runs-on: ubuntu-latest
#
#    permissions:
#      contents: read
#      id-token: write
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Publish package
#        run: npx jsr publish
