name: Publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'jsr.json'
      - 'CHANGELOG.md'
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          token: ${{ secrets.GH_TOKEN }}
          package-name: release-please-action

  publish_jsr:
    name: Publish to JSR
    needs: release-please
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
