name: Publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - "package.json"
      - "jsr.json"
      - "CHANGELOG.md"
permissions:
  contents: write
  pull-requests: write

jobs:
  publish_jsr:
    name: Publish to JSR
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish
